# Generated by Django 2.1.7 on 2020-04-08 12:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='账号')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人')),
                ('address', models.CharField(max_length=256, verbose_name='收件地址')),
                ('zipCode', models.CharField(max_length=6, null=True, verbose_name='邮政编码')),
                ('phone', models.CharField(max_length=11, verbose_name='联系电话')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '地址',
                'verbose_name_plural': '地址',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, verbose_name='账号')),
                ('trackId', models.CharField(max_length=20, verbose_name='标记id')),
                ('goodsNum', models.IntegerField(verbose_name='商品数量')),
                ('goodsPrice', models.IntegerField(verbose_name='商品价格')),
                ('isChose', models.BooleanField(default=True, verbose_name='是否选择')),
                ('img', models.ImageField(upload_to='static\\images\\cart', verbose_name='图片')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('orderId', models.CharField(default='0', max_length=20, verbose_name='订单id')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClothesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20, verbose_name='类型名')),
                ('typeId', models.CharField(max_length=20, verbose_name='类型id')),
                ('childTypeNames', models.CharField(max_length=100, verbose_name='子类名')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '衣服分类',
                'verbose_name_plural': '衣服分类',
            },
        ),
        migrations.CreateModel(
            name='Jacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\goods', verbose_name='图片')),
                ('goodsPrice', models.IntegerField(verbose_name='商品价格')),
                ('praiseNum', models.IntegerField(verbose_name='好评数')),
                ('briefIntro', models.TextField(max_length=100, verbose_name='简介')),
                ('address', models.CharField(max_length=20, verbose_name='所在地')),
                ('stockNum', models.IntegerField(verbose_name='库存')),
                ('goodsLabel', models.CharField(max_length=20, verbose_name='商品标签')),
                ('sellStatus', models.BooleanField(default=True, verbose_name='出售状态')),
                ('childName', models.CharField(max_length=20, verbose_name='子类名')),
                ('childId', models.CharField(max_length=20, verbose_name='子类id')),
                ('trackId', models.CharField(max_length=20, verbose_name='标记id')),
            ],
            options={
                'verbose_name': '上衣',
                'verbose_name_plural': '上衣',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\orderGoods', verbose_name='图片')),
                ('count', models.IntegerField(default=1, verbose_name='商品数目')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '订单商品',
                'verbose_name_plural': '订单商品',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('orderId', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='订单id')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝'), (4, '银联支付')], default=3, verbose_name='支付方式')),
                ('total_count', models.IntegerField(default=1, verbose_name='商品数量')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品总价')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单运费')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='订单状态')),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='支付编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\goods', verbose_name='图片')),
                ('goodsPrice', models.IntegerField(verbose_name='商品价格')),
                ('praiseNum', models.IntegerField(verbose_name='好评数')),
                ('briefIntro', models.TextField(max_length=100, verbose_name='简介')),
                ('address', models.CharField(max_length=20, verbose_name='所在地')),
                ('stockNum', models.IntegerField(verbose_name='库存')),
                ('goodsLabel', models.CharField(max_length=20, verbose_name='商品标签')),
                ('sellStatus', models.BooleanField(default=True, verbose_name='出售状态')),
                ('childName', models.CharField(max_length=20, verbose_name='子类名')),
                ('childId', models.CharField(max_length=20, verbose_name='子类id')),
                ('trackId', models.CharField(max_length=20, verbose_name='标记id')),
            ],
            options={
                'verbose_name': '其它',
                'verbose_name_plural': '其它',
            },
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\goods', verbose_name='图片')),
                ('goodsPrice', models.IntegerField(verbose_name='商品价格')),
                ('praiseNum', models.IntegerField(verbose_name='好评数')),
                ('briefIntro', models.TextField(max_length=100, verbose_name='简介')),
                ('address', models.CharField(max_length=20, verbose_name='所在地')),
                ('stockNum', models.IntegerField(verbose_name='库存')),
                ('goodsLabel', models.CharField(max_length=20, verbose_name='商品标签')),
                ('sellStatus', models.BooleanField(default=True, verbose_name='出售状态')),
                ('childName', models.CharField(max_length=20, verbose_name='子类名')),
                ('childId', models.CharField(max_length=20, verbose_name='子类id')),
                ('trackId', models.CharField(max_length=20, verbose_name='标记id')),
            ],
            options={
                'verbose_name': '下装',
                'verbose_name_plural': '下装',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\recommend', verbose_name='图片')),
                ('redirectUrl', models.CharField(max_length=100, verbose_name='跳转url')),
                ('goodsPrice', models.IntegerField(verbose_name='商品价格')),
                ('stockNum', models.IntegerField(verbose_name='库存数量')),
                ('trackId', models.CharField(max_length=20, verbose_name='标记id')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '推荐新品',
                'verbose_name_plural': '推荐新品',
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\goods', verbose_name='图片')),
                ('goodsPrice', models.IntegerField(verbose_name='商品价格')),
                ('praiseNum', models.IntegerField(verbose_name='好评数')),
                ('briefIntro', models.TextField(max_length=100, verbose_name='简介')),
                ('address', models.CharField(max_length=20, verbose_name='所在地')),
                ('stockNum', models.IntegerField(verbose_name='库存')),
                ('goodsLabel', models.CharField(max_length=20, verbose_name='商品标签')),
                ('sellStatus', models.BooleanField(default=True, verbose_name='出售状态')),
                ('childName', models.CharField(max_length=20, verbose_name='子类名')),
                ('childId', models.CharField(max_length=20, verbose_name='子类id')),
                ('trackId', models.CharField(max_length=20, verbose_name='标记id')),
            ],
            options={
                'verbose_name': '鞋子',
                'verbose_name_plural': '鞋子',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAccount', models.CharField(max_length=20, unique=True, verbose_name='账号')),
                ('userPassword', models.CharField(max_length=20, verbose_name='密码')),
                ('userMail', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('userToken', models.CharField(max_length=50, verbose_name='token值')),
            ],
            options={
                'verbose_name': '会员',
                'verbose_name_plural': '会员',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='static\\images\\wheel', verbose_name='图片')),
                ('redirectUrl', models.CharField(max_length=100, verbose_name='跳转url')),
                ('rankId', models.CharField(max_length=20, verbose_name='等级')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiajiale.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='ordergoods',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jiajiale.OrderInfo', verbose_name='订单'),
        ),
    ]
